name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Code
      uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install Dependencies
      run: dotnet restore
      env:
        DOTNET_NOLOGO: true
    - name: Create Nuget Package
      run: dotnet pack --nologo --configuration Release --no-restore --output artifacts -p:ContinuousIntegrationBuild=true -p:RepositoryCommit="${GITHUB_SHA}" -p:Version=${{ github.event.release.tag_name }}
    - name: Push Nuget Package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push artifacts/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json